### ISSUE TITLE
assign a version tag to releases

### ISSUE THREAD

**Issue by Schlaefer** [PhileCMS/phileInlineImage#2]
without version tags:
- composers throws an error on suggested install method (`php composer.phar require phile/inline-image:*`) because there's no stable release
- using dev-master is not a good solution on automated deployment (supposed content only update may offer sudden "surprises")

(also noticed that on the phile/rss-feed plugin)

**Comment by TiGR** [comment]
+1

That's not even a code change. Just `git tag 1.0.0 && git push --tags` (and make sure packaginst updates).  pinging @james2doyle @NeoBlack

**Comment by james2doyle** [comment]
Done. https://github.com/PhileCMS/phileInlineImage/releases/tag/1.0.0
